apiVersion: v1
kind: Service
metadata:
  name: backend-load-balancer
  labels:
    app: ruby-docker
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      nodePort: 32000
  selector:
    app: ruby-docker
